// USERS MOCK DATA
const COUNTRIES = [
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "Egypt",
  "UK",
  "USA",
  "Canada",
  "Germany",
  "France",
];
const STATUSES_USER = ["active", "inactive", "pending", "banned"] as const;
const NAMES = [
  "Amara Nwosu",
  "Kofi Mensah",
  "Zainab Okafor",
  "David Adeyemi",
  "Fatima Bello",
  "Emeka Eze",
  "Aisha Hassan",
  "Tunde Bakare",
  "Ngozi Okonkwo",
  "Yusuf Abdullahi",
  "Chioma Obi",
  "Seun Adesanya",
  "Ada Obi",
  "Bayo Olawale",
  "Kemi Adebayo",
  "Olumide Fashola",
  "Ify Okafor",
  "Damilola Salako",
  "Chidi Okeke",
  "Funke Akindele",
  "James Smith",
  "Maria Garcia",
  "Wei Chen",
  "Priya Patel",
  "Omar Hassan",
  "Lena Müller",
  "Lucas Martin",
  "Sofia Rossi",
  "Andrei Popescu",
  "Ana Silva",
  "Elena Ivanova",
  "Mehmet Yilmaz",
  "Fatou Diallo",
  "Kwame Asante",
  "Blessing Osei",
  "Taiwo Adeoye",
  "Chiamaka Uba",
  "Hakeem Olajide",
  "Rukayat Sanni",
  "Biodun Fasanya",
  "Nnamdi Okoro",
  "Uchechi Nwankwo",
  "Gbenga Afolabi",
  "Tolani Adeyinka",
  "Abike Lawson",
  "Rotimi Adesina",
  "Folake Ogundimu",
  "Ade Ogundele",
  "Sade Makinde",
  "Tolu Abiola",
];

export const USERS_DATA = NAMES.map((name, i) => ({
  id: i + 1,
  name,
  email: `${name.toLowerCase().replace(/\s+/g, ".")}@example.com`,
  age: 18 + Math.floor(Math.abs(Math.sin(i * 7.3) * 45)),
  country: COUNTRIES[i % COUNTRIES.length],
  status: STATUSES_USER[i % STATUSES_USER.length],
  createdAt: new Date(2022, i % 12, (i % 28) + 1).toISOString().split("T")[0],
  purchases: Math.floor(Math.abs(Math.cos(i * 3.7) * 80)),
}));

// ORDERS MOCK DATA
const PRODUCTS_LIST = [
  "MacBook Pro",
  "iPhone 15",
  "Samsung Galaxy S24",
  "Sony WH-1000XM5",
  "iPad Air",
  "AirPods Pro",
  "Dell XPS 15",
  "LG OLED TV",
  "Nintendo Switch",
  "PS5",
  "Nike Air Max",
  "Adidas Ultraboost",
  "Levi's Jeans",
  "Zara Jacket",
  "H&M Hoodie",
  "The Alchemist",
  "Atomic Habits",
  "Rich Dad Poor Dad",
  "Zero to One",
  "Deep Work",
  "Whey Protein",
  "Yoga Mat",
  "Dumbbells Set",
  "Running Shoes",
  "Gym Gloves",
  "Coffee Maker",
  "Blender",
  "Air Fryer",
  "Rice Cooker",
  "Microwave",
];
const STATUSES_ORDER = [
  "pending",
  "processing",
  "shipped",
  "delivered",
  "cancelled",
] as const;
const REGIONS = [
  "Lagos",
  "Accra",
  "Nairobi",
  "Cairo",
  "London",
  "New York",
  "Berlin",
  "Paris",
  "Toronto",
  "Dubai",
];

export const ORDERS_DATA = Array.from({ length: 50 }, (_, i) => ({
  id: i + 1,
  userId: (i % 30) + 1,
  product: PRODUCTS_LIST[i % PRODUCTS_LIST.length],
  total: Math.round(Math.abs(Math.sin(i * 4.1) * 2000) + 9.99),
  status: STATUSES_ORDER[i % STATUSES_ORDER.length],
  region: REGIONS[i % REGIONS.length],
  createdAt: new Date(2023, i % 12, (i % 28) + 1).toISOString().split("T")[0],
  refunded: i % 7 === 0,
}));

// PRODUCTS MOCK DATA
const CATEGORIES = [
  "electronics",
  "clothing",
  "food",
  "books",
  "sports",
  "home",
] as const;
const PRODUCT_NAMES = [
  "Wireless Earbuds",
  "Smart Watch",
  "Bluetooth Speaker",
  "Laptop Stand",
  "USB Hub",
  "Classic Tee",
  "Slim Fit Chinos",
  "Puffer Jacket",
  "Sneakers",
  "Baseball Cap",
  "Organic Oats",
  "Green Tea",
  "Dark Chocolate",
  "Almond Butter",
  "Protein Bar",
  "Clean Code",
  "The Pragmatic Programmer",
  "System Design Interview",
  "DDIA",
  "SICP",
  "Resistance Bands",
  "Pull-up Bar",
  "Foam Roller",
  "Jump Rope",
  "Kettlebell",
  "Desk Lamp",
  "Cable Management Kit",
  "Monitor Arm",
  "Ergonomic Chair",
  "Standing Desk",
  "Webcam",
  "Mechanical Keyboard",
  "Gaming Mouse",
  "Mousepad XL",
  "Screen Cleaner",
  "Power Bank",
  "Phone Stand",
  "Charging Cable",
  "Screen Protector",
  "Phone Case",
  "Coffee Grinder",
  "French Press",
  "Aeropress",
  "Gooseneck Kettle",
  "Espresso Cups",
  "Notebook A5",
  "Fountain Pen",
  "Sticky Notes",
  "Index Cards",
  "Whiteboard",
];

export const PRODUCTS_DATA = PRODUCT_NAMES.map((name, i) => ({
  id: i + 1,
  name,
  category: CATEGORIES[i % CATEGORIES.length],
  price: Math.round(Math.abs(Math.sin(i * 5.3) * 500) + 4.99),
  stock: Math.floor(Math.abs(Math.cos(i * 2.1) * 300)),
  rating: Math.round((3 + Math.abs(Math.sin(i * 1.7) * 2)) * 10) / 10,
  inStock: i % 6 !== 0,
  createdAt: new Date(2023, i % 12, (i % 28) + 1).toISOString().split("T")[0],
}));

// UNIFIED ACCESSOR
export function getDataBySchema(schemaName: string): Record<string, unknown>[] {
  switch (schemaName) {
    case "users":
      return USERS_DATA as unknown as Record<string, unknown>[];
    case "orders":
      return ORDERS_DATA as unknown as Record<string, unknown>[];
    case "products":
      return PRODUCTS_DATA as unknown as Record<string, unknown>[];
    default:
      return [];
  }
}
